const ORIGIN='https://apex-skills-institute-rmlx0fgdj-ludidil-5352s-projects.vercel.app';
const SITE='https://apexskillsinstitute.co.za';
const SUPABASE_URL='https://vmgmjvakronmkncipzhh.supabase.co';
const SUPABASE_KEY='sb_publishable_KSA8xpm5fMS7IsckTTQEjQ_nCgAh5UB';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cleanPath=p=>{
  if(p==='/index'||p==='/index.html') return '/';
  if(p.endsWith('.html')) return p.slice(0,-5)||'/';
  return p;
};
const canonicalRoute=p=>{
  p=cleanPath(p);
  if(p==='/terms') return '/terms-and-conditions';
  if(p==='/privacy') return '/privacy-policy';
  return p;
};
const cleanInternalUrl=(raw,pagePath)=>{
  if(!raw||raw.startsWith('#')||/^(mailto:|tel:|sms:|javascript:|data:)/i.test(raw)) return raw;
  try{
    const u=new URL(raw,new URL(pagePath,SITE));
    if(u.origin!==SITE) return raw;
    u.pathname=canonicalRoute(u.pathname);
    return `${u.pathname}${u.search}${u.hash}`;
  }catch{return raw}
};
const markCurrentNavigation=(html,pagePath)=>{
  const section=pagePath.startsWith('/schools/')?'/schools':pagePath.startsWith('/programmes/')?'/programmes':canonicalRoute(pagePath);
  return html.replace(/(<header\b[\s\S]*?<nav\b[\s\S]*?<\/nav>)/i,nav=>nav.replace(/<a\b([^>]*?)href=(['"])(.*?)\2([^>]*)>/gi,(m,before,q,href,after)=>{
    const target=cleanInternalUrl(href,pagePath).split(/[?#]/)[0];
    const attrs=`${before}href=${q}${href}${q}${after}`.replace(/\saria-current=(['"])page\1/gi,'');
    const isCta=/\bnav-cta\b/i.test(`${before} ${after}`);
    return target===section&&!isCta?`<a${attrs} aria-current="page">`:`<a${attrs}>`;
  }));
};
const MEDIA='/assets/media/';
const formCss=`<style id="apex-form-feedback">.form-feedback{margin-top:14px;padding:12px 14px;border-radius:8px;background:#eef3fb;color:#07183d}.form-feedback:empty{display:none}.form-feedback.success{background:#e8f6ed;color:#155b31}.form-feedback.error{background:#fff0ed;color:#8c241b}button:disabled{cursor:wait;opacity:.7}</style>`;
const cookieHead='<link rel="stylesheet" href="/assets/cookie-consent.css?v=1.0">';
const cookieScript='<script src="/assets/cookie-consent.js?v=1.0" defer></script>';
const mobileNavCss=`<style id="apex-mobile-navigation">@media(max-width:980px){html{scroll-padding-top:84px}body{padding-top:74px}header{position:fixed!important;top:0!important;right:0!important;left:0!important;width:100%!important;z-index:1000!important}header nav{position:fixed!important;top:74px!important;right:0!important;bottom:auto!important;left:0!important;display:flex!important;flex-direction:column!important;align-items:stretch!important;justify-content:flex-start!important;gap:0!important;width:100%!important;height:calc(100dvh - 74px)!important;min-height:calc(100dvh - 74px)!important;max-height:none!important;margin:0!important;padding:22px 24px calc(24px + env(safe-area-inset-bottom))!important;background:linear-gradient(180deg,#fff 0%,#fbfcfe 100%)!important;box-shadow:0 14px 28px rgba(7,24,61,.12)!important;z-index:999!important;overflow-x:hidden!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important;transform:translateY(-10px)!important;transition:opacity .18s ease,transform .18s ease,visibility 0s linear .18s!important}header nav.open{visibility:visible!important;opacity:1!important;pointer-events:auto!important;transform:none!important;transition:opacity .18s ease,transform .18s ease!important}header nav a{display:block!important;width:100%!important;flex:0 0 auto!important;margin:0!important;padding:15px 10px!important;color:#07183d!important;border-bottom:1px solid #e8edf4!important}header nav a[aria-current=page]{background:linear-gradient(90deg,#fff5e8,transparent)!important;color:#b94808!important}header nav .nav-cta{margin-top:14px!important;border:0!important;text-align:center!important;background:#d8aa42!important;color:#07183d!important;box-shadow:0 10px 24px rgba(216,170,66,.22)!important}header nav:after{content:"PRACTICAL LEARNING. REAL CAPABILITY.\A\A9 Schools  ·  60 programmes  ·  Applied learning"!important;display:block!important;flex:0 0 auto!important;margin:20px 0 0!important;margin-top:auto!important;padding:24px 22px!important;border-radius:18px!important;background:radial-gradient(circle at 90% 10%,#163b82 0,#0b255d 42%,#07183d 100%)!important;color:#fff!important;font-size:.88rem!important;font-weight:700!important;line-height:1.55!important;letter-spacing:.02em!important;white-space:pre-line!important;box-shadow:0 16px 32px rgba(7,24,61,.18)!important}body.menu-open{overflow:hidden!important;overscroll-behavior:none!important}.fine{display:block!important}.fine>span{display:block!important;width:100%!important}.fine>span+span{margin-top:14px!important;line-height:1.8!important}.fine a{display:inline!important;margin:0!important;white-space:normal!important}}@media(max-width:600px){html{scroll-padding-top:78px}body{padding-top:68px}header nav{top:68px!important;height:calc(100dvh - 68px)!important;min-height:calc(100dvh - 68px)!important}}</style>`;
const mobileNavPolishCss=`<style>@media(max-width:980px){header nav:after{content:"Practical learning. Real capability.  •  9 Schools  •  60 programmes"!important}}</style>`;
const imageForRoute=pagePath=>{
  const p=canonicalRoute(pagePath);
  if(p==='/') return ['apex_02_team_collaboration.webp','Apex learners collaborating around a laptop'];
  if(p==='/schools') return ['apex_04_classroom_learning.webp','Adult learners participating in an Apex classroom session'];
  if(p==='/programmes') return ['apex_01_woman_studying_laptop.webp','Apex learner studying with a laptop and written notes'];
  if(p==='/for-organisations') return ['apex_08_corporate_training_meeting.webp','Organisation-based professional training and discussion'];
  if(p==='/about') return ['apex_07_graduate_diploma.webp','Learner celebrating completion of a learning programme'];
  if(p==='/contact') return ['apex_06_professional_woman_tablet.webp','Professional learner using a tablet in the workplace'];
  if(p==='/payment-flexibility') return ['apex_03_professional_man_laptop.webp','Professional reviewing programme information on a laptop'];
  if(p==='/faculty-network') return ['apex_08_corporate_training_meeting.webp','Experienced facilitator leading an applied professional learning session'];
  if(p.startsWith('/schools/')){
    const slug=p.split('/').pop();
    const school={
      'business-entrepreneurship':'apex_03_professional_man_laptop.webp',
      'finance-administration':'apex_06_professional_woman_tablet.webp',
      'human-resources-public-finance':'apex_08_corporate_training_meeting.webp',
      'ohs-risk-compliance':'apex_04_classroom_learning.webp',
      'digital-technology-data':'apex_09_student_books.webp',
      'project-operations-built-environment':'apex_08_corporate_training_meeting.webp',
      'public-sector-municipal-management':'apex_06_professional_woman_tablet.webp',
      'supply-chain-fleet-logistics':'apex_02_team_collaboration.webp',
      'agriculture-rural-enterprise':'apex_01_woman_studying_laptop.webp'
    }[slug]||'apex_04_classroom_learning.webp';
    return [school,'Apex applied-learning participants'];
  }
  if(p.startsWith('/programmes/')){
    if(/farm|agri|rural|cooperative/.test(p)) return ['apex_01_woman_studying_laptop.webp','Learner developing practical enterprise capability'];
    if(/digital|excel|cyber|data|sql|microsoft|ai-/.test(p)) return ['apex_09_student_books.webp','Learner building practical digital and workplace capability'];
    if(/bookkeeping|payroll|finance|budget|office|records|administration/.test(p)) return ['apex_06_professional_woman_tablet.webp','Professional developing finance and administration capability'];
    if(/health|safety|risk|incident|popia|compliance/.test(p)) return ['apex_04_classroom_learning.webp','Participants in a structured professional learning environment'];
    if(/project|operations|facilities|construction|monitoring/.test(p)) return ['apex_08_corporate_training_meeting.webp','Applied organisational and project learning session'];
    if(/public|municipal|government|procurement|supply|logistics|fleet|inventory|supplier/.test(p)) return ['apex_02_team_collaboration.webp','Apex learners collaborating on an applied workplace task'];
    return ['apex_03_professional_man_laptop.webp','Professional learner completing an applied programme activity'];
  }
  return null;
};
const mediaCss=`<style id="apex-media-quality">header nav a[aria-current="page"]{color:#07183d;box-shadow:inset 0 -3px #d85700}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #e56a14!important;outline-offset:3px}.brand img,.footer-logo{height:auto;image-rendering:auto}.page-hero-media,.school-hero-media{background:#07183d;overflow:hidden}.page-hero-media img,.school-hero-media img{width:100%;height:100%;object-fit:cover;object-position:center;display:block}.apex-context-media{max-width:1180px;margin:0 auto 42px;padding:0 24px}.apex-context-media div{overflow:hidden;background:#07183d;aspect-ratio:16/7}.apex-context-media img{width:100%;height:100%;display:block;object-fit:cover;object-position:center}.apex-context-media figcaption{margin-top:10px;color:#475569;font-size:.82rem}@media(max-width:760px){header nav a[aria-current="page"]{box-shadow:none;background:#eef3fb}.apex-context-media{padding:0 18px;margin-bottom:28px}.apex-context-media div{aspect-ratio:4/3}}</style>`;
const applyRouteImage=(html,pagePath)=>{
  const choice=imageForRoute(pagePath);
  let out=html.replace('</head>',`${mediaCss}${formCss}${mobileNavCss}${mobileNavPolishCss}${cookieHead}</head>`);
  if(!choice) return out;
  const [file,alt]=choice,src=`${MEDIA}${file}`;
  if(/class="(?:page-hero-media|school-hero-media)"/i.test(out)) return out.replace(/(<div class="(?:page-hero-media|school-hero-media)"[^>]*>[\s\S]*?<img\b)([^>]*)(>)/i,(m,start,attrs,end)=>`${start}${attrs.replace(/\bsrc="[^"]*"/i,`src="${src}"`).replace(/\balt="[^"]*"/i,`alt="${alt}"`)}${end}`);
  if(pagePath==='/') return out.replace(/(<img\b[^>]*?alt=")Learners collaborating around a laptop("[^>]*?src=")([^"]+)/i,`$1${alt}$2${src}`);
  if(pagePath.startsWith('/programmes/')){
    const figure=`<figure class="apex-context-media"><div><img src="${src}" alt="${alt}" width="1536" height="1024" loading="eager" decoding="async"></div></figure>`;
    return out.replace(/(<\/section>\s*)(<section class="section">)/i,`$1${figure}$2`);
  }
  return out;
};
const cleanHtml=(html,pagePath)=>{
  let out=html.replace(/\b(href|src|action)=(['"])(.*?)\2/gi,(m,a,q,u)=>`${a}=${q}${cleanInternalUrl(u,pagePath)}${q}`);
  out=out.replace(/info@apexskills\.ac\.za/gi,'info@apexskillsinstitute.co.za');
  out=out.replace(/\/assets\/site\.js\?v=[^'"<]+/g,'/assets/site.js?v=2.16.0');
  out=out.replace(/<a\b([^>]*?)href="\/privacy-policy"([^>]*)>Privacy<\/a>\s*·\s*<a\b([^>]*?)href="\/terms-and-conditions"([^>]*)>Terms<\/a>/i,'<a$1href="/privacy-policy"$2>Privacy Policy</a> · <a$3href="/terms-and-conditions"$4>Terms &amp; Conditions</a> · <a href="/disclaimer" style="display:inline;margin:0">Disclaimer</a>');
  out=out.replace(/(<a[^>]+href="\/disclaimer"[^>]*>Disclaimer<\/a>)/i,'$1 · <a href="/cookie-policy" style="display:inline;margin:0">Cookie Policy</a> · <a href="#cookie-settings" class="cookie-settings-link" style="display:inline;margin:0">Cookie Settings</a>');
  out=out.replace(/(<h3 class="footer-heading">Institution<\/h3>[\s\S]*?<a href="\/about">About Apex<\/a>)/i,'$1<a href="/faculty-network">Faculty Network</a>');
  if(!out.includes('/assets/cookie-consent.js')) out=out.replace('</body>',`${cookieScript}</body>`);
  return applyRouteImage(markCurrentNavigation(out,pagePath),pagePath);
};

function shell({title,description,label,heading,body}){
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0A1B4A"><title>${esc(title)} | Apex Skills Institute</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${SITE}${locationFor(title)}"><link rel="icon" href="/assets/favicon.png"><link rel="stylesheet" href="/assets/styles.css?v=2.13.0">${cookieHead}<meta property="og:site_name" content="Apex Skills Institute"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)} | Apex Skills Institute"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${SITE}${locationFor(title)}"><meta property="og:image" content="${SITE}/assets/apex-social-card-v2.jpg"><meta name="twitter:card" content="summary_large_image"></head><body><a class="skip" href="#main">Skip to content</a><header><div class="wrap head"><a class="brand" href="/" aria-label="Apex Skills Institute home"><img src="/assets/apex-logo-light.webp" alt="Apex Skills Institute"></a><nav aria-label="Primary navigation"><a href="/schools">Schools</a><a href="/programmes">Programmes</a><a href="/for-organisations">For Organisations</a><a href="/about">About</a><a href="/contact">Contact</a><a class="nav-cta" href="/contact">Enquire</a></nav><button class="menu" aria-expanded="false" aria-label="Open menu"><span></span><span></span><span></span></button></div></header><main id="main"><section class="page-hero"><div class="wrap"><div class="eyebrow">${esc(label)}</div><h1>${esc(heading)}</h1><p class="lead">Effective 21 August 2026 · Version 1.0</p><div class="status-note"><strong>Draft — Legal Review.</strong> This page is published for institutional transparency and remains subject to review by an appropriate South African legal or privacy professional.</div></div></section><section class="section"><div class="wrap" style="max-width:900px"><div class="legal-copy">${body}</div></div></section></main>${footer()}<script src="/assets/site.js?v=2.13.0"></script>${cookieScript}</body></html>`}
function locationFor(title){return title==='Terms and Conditions'?'/terms-and-conditions':title==='Privacy Policy'?'/privacy-policy':title==='Cookie Policy'?'/cookie-policy':'/disclaimer'}
function footer(){return `<footer><div class="wrap"><div class="foot-grid"><div><img class="footer-logo" src="/assets/apex-logo-dark.webp" alt="Apex Skills Institute"><p>Practical learning for real capability.</p></div><div><h3 class="footer-heading">Explore</h3><a href="/schools">Schools</a><a href="/programmes">Programmes</a><a href="/for-organisations">For Organisations</a></div><div><h3 class="footer-heading">Legal</h3><a href="/terms-and-conditions">Terms and Conditions</a><a href="/privacy-policy">Privacy Policy</a><a href="/cookie-policy">Cookie Policy</a><a href="#cookie-settings" class="cookie-settings-link">Cookie Settings</a><a href="/disclaimer">Disclaimer</a><a href="/payment-flexibility">Payment Flexibility</a></div><div><h3 class="footer-heading">Contact</h3><a href="tel:+27731433319">073 143 3319</a><a href="mailto:info@apexskillsinstitute.co.za">info@apexskillsinstitute.co.za</a><span>Port Elizabeth, Eastern Cape</span></div></div><div class="fine"><span>Apex Skills Institute (Pty) Ltd · 2026/153633/07</span><span>© 2026 Apex Skills Institute</span></div></div></footer>`}
const s=(h,p)=>`<section><h2>${h}</h2>${p}</section>`;
const list=a=>`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const TERMS=shell({title:'Terms and Conditions',description:'Terms governing the Apex Skills Institute website, programme enrolment, fees, payment flexibility, learning and related services.',label:'Legal',heading:'Terms and Conditions',body:
 s('1. About Apex Skills Institute',`<p>Apex Skills Institute (Pty) Ltd (“Apex”, “we”, “us” or “our”) is a South African private company providing professional-development, applied-learning, workforce-development and organisational-capability programmes.</p><p><strong>Registration number:</strong> 2026/153633/07<br><strong>Registered office:</strong> 27 Trichardt Street, Parsons Hill, Port Elizabeth, Eastern Cape, 6001, South Africa.</p>`)+
 s('2. Scope of these Terms',`<p>These Terms apply, where relevant, to individual and prospective learners, website users, applicants, persons purchasing or participating in Apex programmes, organisations arranging learning interventions and users of Apex digital services. Separate signed agreements may apply to organisation-based training, funded projects and customised interventions.</p>`)+
 s('3. Programme status',`<p>Unless expressly stated otherwise for a specific programme, an Apex programme is an <strong>institutional, non-credit-bearing learning programme</strong>. Apex does not represent such a programme as an NQF-registered qualification, QCTO- or SETA-accredited programme, SAQA-registered qualification, professional designation or other externally accredited or registered programme.</p>`)+
 s('4. Programme information',`<p>Apex takes reasonable steps to keep programme descriptions, outcomes, duration, delivery information and fees accurate. Information may be updated to improve learning quality, maintain relevance, reflect regulatory or industry developments, correct errors or accommodate reasonable operational requirements.</p>`)+
 s('5. Applications and enrolment',`<p>Submitting an application does not automatically constitute acceptance or enrolment. An enrolment is confirmed only when Apex has communicated acceptance and applicable enrolment requirements have been satisfied. Apex may decline or cancel an application where materially false, misleading or fraudulent information has been supplied, subject to applicable law.</p>`)+
 s('6. Programme fees',`<p>The Programme Fee is the price displayed on the relevant programme page or otherwise formally quoted by Apex. Apex may change prices prospectively, but a subsequent price change will not retrospectively alter a Programme Fee already agreed for a confirmed enrolment except where permitted by law or expressly agreed.</p>`)+
 s('7. Payment Flexibility',`<p>Certain Apex programmes may offer flexible monthly payments. Where available, this allows the agreed Programme Fee to be paid over an approved payment period. Apex does not increase the Programme Fee solely because an eligible learner chooses monthly payment.</p><table><tr><th>Payment option</th><th>Amount</th></tr><tr><td>Programme Fee</td><td>R4,950</td></tr><tr><td>Pay in full</td><td>R4,950</td></tr><tr><td>Flexible monthly option</td><td>2 × R2,475</td></tr><tr><td>Total payable</td><td>R4,950</td></tr></table><p>Not every programme is necessarily eligible. See <a href="/payment-flexibility">Payment Flexibility</a>.</p>`)+
 s('8. Payment obligations',`<p>A learner selecting monthly payment agrees to pay each instalment on the disclosed dates. Instalments form part of payment of the agreed Programme Fee and are not separate programme purchases. Apex will not impose an undisclosed interest charge, finance charge or payment-plan premium.</p>`)+
 s('9. Cancellations, withdrawals and refunds',`<p>Apex recognises applicable consumer rights under South African law. Outcomes may depend on timing, commencement, digital materials or services already supplied, the nature and reason for cancellation and services already performed. Where applicable, Apex may charge only a lawful and reasonable cancellation amount. Nothing in these Terms waives a statutory consumer right that cannot legally be waived.</p>`)+
 s('10. Cooling-off and electronic transactions',`<p>Where a statutory cooling-off or cancellation right applies, Apex will respect that right in accordance with applicable South African law.</p>`)+
 s('11. Programme commencement and scheduling',`<p>Programme commencement may be subject to operational requirements, including minimum viable cohort sizes where applicable. Apex will communicate confirmed commencement information and reasonable options where postponement or rescheduling is required.</p>`)+
 s('12. Changes or cancellation by Apex',`<p>Apex may reasonably reschedule sessions, change facilitators, modify delivery arrangements, update learning materials or adjust sequencing without materially diminishing the programme purchased. If Apex cancels a programme without a reasonable alternative, affected learners will receive an appropriate remedy in accordance with applicable law.</p>`)+
 s('13. Learning materials and intellectual property',`<p>Apex owns or lawfully uses its learner guides, facilitator guides, presentations, toolkits, templates, assessments, rubrics, case studies, videos and digital resources. Enrolment grants a limited, personal, non-transferable learning-use right. Materials may not be sold, publicly uploaded, commercially reproduced, redistributed or represented as the learner’s own without written permission.</p>`)+
 s('14. Digital learning and account security',`<p>Digital-learning accounts are personal. Learners must protect their credentials. Temporary interruptions may occur because of maintenance, telecommunications failures, third-party systems or circumstances outside Apex’s reasonable control.</p>`)+
 s('15. Learner conduct',`<p>Learners are expected to act respectfully and professionally. Apex may proportionately address harassment, discrimination, threats, fraud, academic dishonesty, deliberate disruption, unauthorised system access, impersonation and serious intellectual-property infringement.</p>`)+
 s('16. Assessment',`<p>Assessment requirements vary and may include practical exercises, applied assignments, case analysis, workplace scenarios, projects, presentations, portfolios or capstone outputs. Attendance alone does not necessarily constitute successful completion.</p>`)+
 s('17. Academic and assessment integrity',`<p>Plagiarism, impersonation, falsification of evidence, unauthorised collaboration or other material misconduct may result in rejection of an assessment or other appropriate action. AI-tool use may be regulated by programme-specific instructions.</p>`)+
 s('18. Certificates',`<p>Certificate type depends on the programme and successful satisfaction of requirements. An Apex certificate does not confer an NQF qualification, professional designation, statutory licence or external accreditation unless expressly stated.</p>`)+
 s('19. Organisation-based training',`<p>Organisation training may be governed by a separate proposal, quotation, service agreement, purchase order or contract. Organisation pricing is quotation-based and individual website prices do not automatically determine organisation-based pricing.</p>`)+
 s('20. Facilitators and subject-matter experts',`<p>Apex may use appropriately selected employees, independent facilitators, practitioners, subject-matter experts, assessors, moderators or guest speakers. A particular facilitator is not guaranteed unless expressly agreed.</p>`)+
 s('21. External services and links',`<p>Third-party platforms, payment services, software and websites are governed by their own terms and privacy practices. A link does not necessarily constitute endorsement of every third-party statement, product or service.</p>`)+
 s('22. Privacy',`<p>Apex processes personal information in accordance with applicable South African data-protection law and the <a href="/privacy-policy">Privacy Policy</a>.</p>`)+
 s('23. Limitation and statutory rights',`<p>Apex will exercise reasonable care in providing its services. To the maximum extent permitted by law, Apex is not responsible for indirect losses arising from circumstances outside its reasonable control or reliance on educational content outside its intended context. Nothing excludes liability or consumer rights where doing so would be unlawful.</p>`)+
 s('24. Complaints',`<p>Apex encourages concerns to be raised directly with sufficient information to identify the programme, issue and requested resolution. Nothing prevents use of an external statutory right or remedy.</p>`)+
 s('25. Governing law',`<p>These Terms are governed by the laws of the Republic of South Africa and applicable mandatory consumer-protection jurisdiction.</p>`)+
 s('26. Changes to these Terms',`<p>Apex may update these Terms. The current version and effective date will be published here. Material changes affecting an existing contractual relationship will be dealt with in accordance with applicable law.</p>`)+
 s('27. Contact',`<p>Questions may be submitted through the <a href="/contact">Contact page</a> or to <a href="mailto:chairman@apexskillsinstitute.co.za">chairman@apexskillsinstitute.co.za</a>.</p>`)
});
const PRIVACY=shell({title:'Privacy Policy',description:'How Apex Skills Institute processes and protects personal information in accordance with South Africa’s Protection of Personal Information Act (POPIA).',label:'Privacy & POPIA',heading:'Privacy & POPIA Policy',body:
 `<p><strong>Your information. Handled responsibly.</strong></p><p>Apex Skills Institute (Pty) Ltd respects the privacy of learners, prospective learners, clients, Faculty Network applicants, website users and other individuals whose personal information it processes. This Policy explains how Apex collects, uses, stores, discloses and protects personal information in accordance with the <strong>Protection of Personal Information Act 4 of 2013 (POPIA)</strong> and other applicable South African law.</p>`+
 s('1. Responsible party',`<p>For purposes of POPIA, Apex Skills Institute (Pty) Ltd is the responsible party for personal information processed for its own purposes.</p><p><strong>Apex Skills Institute (Pty) Ltd</strong><br>Registration number: 2026/153633/07<br>27 Trichardt Street, Parsons Hill, Port Elizabeth, Eastern Cape, 6001, South Africa.</p>`)+
 s('2. Application of POPIA',`<p>Apex processes personal information in accordance with POPIA’s conditions for lawful processing:</p>${list(['Accountability','Processing limitation','Purpose specification','Further processing limitation','Information quality','Openness','Security safeguards','Data-subject participation'])}<p>Personal information will be processed only for a lawful and appropriate purpose.</p>`)+
 s('3. Personal information',`<p>Personal information includes information relating to an identifiable living natural person and, where applicable, an identifiable existing juristic person. Depending on the relationship, Apex may process:</p>${list(['Names and surnames','Contact details and location','Identification information where legitimately required','Education, qualification, employment and professional information','Programme selections, applications and enrolments','Assessment, learning and certification records','Communications','Payment and transaction records','Organisation or client information','Technical website information','Information voluntarily supplied'])}<p>Apex seeks to collect only information reasonably relevant to its stated purpose.</p>`)+
 s('4. Lawful purposes for processing',`<p>Apex may process information to provide a requested service; process an application or enrolment; perform or prepare a contract; manage learning, assessment, certification and payments; respond to enquiries; manage organisation engagements and Faculty Network applications; comply with legal obligations; protect legitimate interests; maintain security; improve services; and conduct lawful marketing.</p><p>Where Apex relies on consent, it will request consent for a specific, explained purpose. Consent may be withdrawn, subject to lawful consequences.</p>`)+
 s('5. Purpose limitation',`<p>Information is collected for specific, explicitly defined and lawful purposes. Apex will not use it for an unrelated purpose unless further processing is permitted by POPIA or another lawful basis applies.</p><p>Faculty Network information is primarily used to evaluate suitability, verify information where appropriate, categorise expertise, contact applicants, manage the faculty pipeline, identify potential assignments and manage subsequent professional engagements. Submission does not guarantee appointment or work.</p>`)+
 s('6. Special personal information',`<p>Apex will not intentionally request or process special personal information unless a lawful basis exists and it is reasonably necessary for a defined purpose. This may include information concerning religious or philosophical beliefs, race or ethnic origin, trade-union membership, political persuasion, health or sex life, biometric information, or criminal behaviour. Do not submit such information unless Apex requests it through an authorised process or it is necessary for a lawful purpose.</p>`)+
 s('7. Children’s personal information',`<p>Apex will not intentionally process children’s personal information unless permitted by POPIA or other applicable law and any required consent or authorisation has been obtained. Programmes intended for minors will use appropriate additional safeguards.</p>`)+
 s('8. Faculty Network information',`<p>Faculty applicants may provide names, contact information, location, professional profile, employment history, qualifications, registrations, expertise, sector and facilitation experience, delivery preferences, languages, geographic availability, a CV or supporting documents, and rate expectations where requested.</p><p>Initial applications should not require unnecessary banking, tax or identity-document information. Such information may be requested later only where reasonably required for lawful contractor onboarding, contracting, payment or compliance.</p>`)+
 s('9. Direct marketing',`<p>Apex will manage direct marketing in accordance with POPIA and applicable electronic-communications law. Where consent is required, it will be requested separately and transparently.</p><p>Faculty application or learner-service consent does not constitute marketing consent. Marketing consent is optional, separate, clearly distinguishable, unselected by default and capable of being withdrawn. Recipients may unsubscribe using the mechanism provided or by contacting the Information Officer.</p>`)+
 s('10. Operators and service providers',`<p>Apex may appoint website, hosting, learning-platform, payment, cloud-storage, communications, assessment, quality-assurance, professional-advisory, technology and security providers to process information on its behalf. Apex will seek to ensure operators act only for authorised purposes and implement appropriate safeguards.</p>`)+
 s('11. Cross-border transfers',`<p>Some providers may store or process information outside South Africa. Apex will take reasonable steps to ensure transfers are lawful and the information receives an appropriate level of protection in accordance with POPIA.</p>`)+
 s('12. Security safeguards',`<p>Apex will implement reasonable technical and organisational safeguards designed to protect information against loss, damage, unauthorised access, disclosure, alteration, destruction and misuse. Faculty records and supporting documents must be stored in protected systems with appropriate access controls. No information system can be guaranteed completely secure.</p>`)+
 s('13. Personal-information compromise',`<p>If Apex reasonably believes information has been accessed or acquired by an unauthorised person, it will assess and respond to the incident. Where POPIA requires it, affected data subjects and the Information Regulator will be notified in accordance with applicable requirements.</p>`)+
 s('14. Data quality',`<p>Apex will take reasonably practicable steps to keep personal information complete, accurate, not misleading and updated where necessary. Individuals should notify Apex when information changes or is inaccurate.</p>`)+
 s('15. Retention',`<p>Apex will not retain information longer than necessary for its collection purpose unless retention is required or permitted by law. Retention may be necessary for contractual, enrolment, academic, assessment, financial, legal, regulatory, dispute-management or legitimate operational purposes, or to establish or defend legal claims. Unsuccessful Faculty applications will not automatically be retained indefinitely.</p>`)+
 s('16. Data-subject rights',`<p>Subject to applicable law, a data subject may have the right to be notified of collection; ask whether Apex holds their information; request access, correction or updating; request deletion or destruction where appropriate; object to certain processing or direct marketing; withdraw consent; lodge a complaint; and seek available remedies.</p><p>Apex may require sufficient information to verify the requester’s identity and locate the relevant record.</p>`)+
 s('17. Privacy-rights request process',`<ol><li>Contact the Information Officer by email.</li><li>Describe the information or processing activity concerned.</li><li>Explain the request clearly.</li><li>Provide reasonable information to verify your identity.</li><li>Include supporting information that may help Apex locate the record.</li></ol><p>Apex may request additional information reasonably necessary to process the request securely and lawfully.</p>`)+
 s('18. Information Officer',`<p><strong>Langa Ludidi</strong><br>Information Officer<br>Apex Skills Institute (Pty) Ltd<br>Email: <a href="mailto:chairman@apexskillsinstitute.co.za">chairman@apexskillsinstitute.co.za</a></p><p>This address is reserved for privacy-rights requests, retention concerns, consent withdrawals, direct-marketing objections, Faculty Network privacy enquiries and POPIA complaints. General enquiries must use <a href="mailto:info@apexskillsinstitute.co.za">info@apexskillsinstitute.co.za</a>.</p>`)+
 s('19. Complaints to the Information Regulator',`<p>Individuals are encouraged to contact the Information Officer first so Apex can consider and address the concern. A person retains the right to approach the <a href="https://inforegulator.org.za/" rel="noopener noreferrer">South African Information Regulator</a> where permitted by law.</p>`)+
 s('20. Cookies and website technologies',`<p>Apex may use cookies and similar technologies for essential operation, security, preferences, analytics, performance and other lawful purposes. Where required, appropriate notices and choices will be provided, including ways to manage non-essential cookies. See the <a href="/cookie-policy">Cookie Policy</a> or open <a href="#cookie-settings" class="cookie-settings-link">Cookie Settings</a>.</p>`)+
 s('21. Automated decision-making',`<p>Apex will not subject a data subject to a decision with legal or similarly significant effects based solely on automated processing unless permitted by law and appropriate safeguards exist. Where applicable, Apex will explain the process and available means of requesting human intervention or review.</p>`)+
 s('22. Policy updates',`<p>Apex may update this Policy as its systems, services, activities or legal obligations develop. The latest version and effective date will be published on this page.</p>`)
});
const COOKIE=shell({title:'Cookie Policy',description:'Learn how Apex Skills Institute uses cookies and similar technologies, how to manage your preferences and how to contact the Information Officer.',label:'Privacy & POPIA',heading:'Cookie Policy',body:
 s('1. Introduction',`<p>This Cookie Policy explains how Apex Skills Institute (Pty) Ltd uses cookies and similar technologies when you visit or use the Apex website. Read it together with the <a href="/privacy-policy">Privacy Policy</a> and <a href="/terms-and-conditions">Terms and Conditions</a>.</p><p>Apex uses cookies or similar technologies to support website operation, improve performance, understand website use and, where permitted, support communications and marketing.</p>`)+
 s('2. What are cookies?',`<p>A cookie is a small text file placed on a device when a website is visited. Cookies may remember preferences, sessions, pages viewed, interactions, security information and technical browser or device information. Similar technologies include pixels, tags, software development kits and local storage.</p><p>Cookies do not necessarily identify a person by name, but information associated with a cookie or online identifier may constitute personal information where it can reasonably be linked to an identifiable person.</p>`)+
 s('3. Types of cookies we may use',`<h3>3.1 Strictly necessary</h3><p>Required for navigation, secure areas, forms, session management, fraud prevention, security, cookie preferences, accessibility and core functionality. These cannot generally be disabled through the preference tool.</p><h3>3.2 Preference</h3><p>Remember choices such as language, region, display settings, cookie choices and previously selected options.</p><h3>3.3 Analytics and performance</h3><p>May help Apex understand pages visited, time on page, navigation paths, referrals, devices, errors, general location and performance. Where reasonably possible, analytics should be aggregated or de-identified.</p><h3>3.4 Marketing and advertising</h3><p>Where used, these may measure campaign performance, content interactions, advertising frequency, relevant communications and conversions. They will not be activated unless the required consent has been provided.</p><h3>3.5 Third-party cookies</h3><p>Integrated analytics, video, payment, social-media, advertising, map or other external providers may place cookies under their own policies. Apex should review and document each active third-party script, its purpose, information collected and cross-border processing.</p>`)+
 s('4. Lawful use of cookies',`<p>Apex uses cookies and similar technologies for specific, lawful and transparent purposes, consistently with POPIA, applicable electronic-communications and e-commerce requirements, the Apex Privacy Policy and relevant provider requirements. Where a technology is not strictly necessary, Apex will seek consent where required.</p>`)+
 s('5. Cookie consent',`<p>On a first visit, the consent interface allows visitors to accept all, reject non-essential technologies or manage categories. Declining is presented as an equally accessible choice. Optional technologies remain blocked until the relevant choice is recorded.</p><p>Apex records the consent date and time, category choices, status and Policy version in the visitor’s browser. Apex currently stores this preference locally on the visitor’s device and does not use it to identify the visitor by name.</p>`)+
 s('6. Changing or withdrawing consent',`<p>Preferences may be changed or withdrawn at any time using <a href="#cookie-settings" class="cookie-settings-link">Cookie Settings</a> in the footer. Cookies or stored website data can also be managed through browser settings. Disabling necessary technologies may affect functionality. Withdrawal does not affect processing that lawfully occurred before withdrawal.</p>`)+
 s('7. Current cookie and technology schedule',`<p>This schedule reflects the website configuration as published. It must be reviewed whenever analytics, advertising, video, payments, forms, chat, social media, marketing pixels or CRM integrations change.</p><table><thead><tr><th>Technology</th><th>Provider</th><th>Category</th><th>Purpose</th><th>Duration</th><th>Information</th><th>Consent</th></tr></thead><tbody><tr><td>apex_cookie_preferences_v1 (local storage)</td><td>Apex</td><td>Necessary</td><td>Stores cookie-category choices and policy version</td><td>Until browser data is cleared or the Policy version changes</td><td>Consent timestamp and category choices; no name or contact details</td><td>No — necessary to remember the user’s choice</td></tr></tbody></table><p><strong>Current position:</strong> Apex does not presently activate optional analytics or marketing technologies through this consent system. Any future non-essential script must be registered and blocked until the relevant consent is recorded.</p>`)+
 s('8. Personal information and analytics',`<p>If analytics are introduced, Apex will consider IP masking, aggregated reporting, restricted access, shorter retention, disabled advertising features, limited user-level tracking and documented provider processing.</p>`)+
 s('9. Cross-border processing',`<p>Some future third-party providers may process information outside South Africa. Apex will assess providers and manage transfers in accordance with applicable data-protection requirements, making relevant provider policies available where appropriate.</p>`)+
 s('10. Children',`<p>The website is not intended to collect children’s information without a lawful basis and required consent or authorisation. Features directed at minors will require additional privacy and consent safeguards.</p>`)+
 s('11. Information Officer',`<p><strong>Langa Ludidi</strong><br>Information Officer<br>Apex Skills Institute (Pty) Ltd<br>Email: <a href="mailto:chairman@apexskillsinstitute.co.za">chairman@apexskillsinstitute.co.za</a></p><p>Contact the Information Officer about cookie-related information, correction, retention, withdrawal, objections, third-party providers or POPIA concerns. General enquiries should use <a href="mailto:info@apexskillsinstitute.co.za">info@apexskillsinstitute.co.za</a>.</p>`)+
 s('12. Policy updates',`<p>Apex may update this Policy when the website, technologies, providers or legal obligations change. The current version and effective date will be published on this page.</p>`)
});
const DISCLAIMER=shell({title:'Disclaimer',description:'Important information about Apex programme status, educational content, professional advice, outcomes and website information.',label:'Legal',heading:'Website and Programme Disclaimer',body:
 s('Programme status',`<p>Unless expressly stated otherwise for a specific programme, Apex programmes are institutional, non-credit-bearing professional-development programmes. They are not represented as NQF-registered qualifications or as QCTO-, SETA-, SAQA- or otherwise externally accredited programmes unless specifically stated.</p>`)+
 s('Educational information',`<p>Apex programmes are designed for learning and capability development. Content concerning law, finance, taxation, occupational health and safety, human resources, procurement, technology, agriculture, risk, compliance or other professional subjects is educational and does not replace advice tailored to a person’s or organisation’s circumstances.</p>`)+
 s('Employment and career outcomes',`<p>Participation or completion does not guarantee employment, promotion, salary increase, professional registration or career advancement.</p>`)+
 s('Tender and procurement outcomes',`<p>Tender, procurement and supplier-development programmes build knowledge and practical capability but do not guarantee CSD approval, tender eligibility or responsiveness, contract awards, government business or any other procurement outcome.</p>`)+
 s('Business and funding outcomes',`<p>Business, entrepreneurship and funding-readiness programmes do not guarantee business success, funding approval, investment, loans, grants, revenue, profitability or market access.</p>`)+
 s('Technology and software',`<p>Technology, AI, cybersecurity, Microsoft, data and software-related content may be affected by product updates and technological change. Third-party product names and trademarks remain the property of their respective owners.</p>`)+
 s('Accuracy and currency',`<p>Apex seeks to maintain accurate and useful information, but content may change as laws, technologies, industry practices and programme designs develop. Users should verify information where decisions carry significant legal, financial, safety or professional consequences.</p>`)+
 s('External links',`<p>Links are provided for convenience or reference. Apex does not control independently operated third-party websites and does not necessarily endorse all of their content.</p>`)+
 s('Limitation',`<p>Nothing on this page excludes liability or statutory rights that cannot lawfully be excluded. Please also read the <a href="/terms-and-conditions">Terms and Conditions</a> and <a href="/privacy-policy">Privacy Policy</a>.</p>`)
});
const LEGAL={'/terms-and-conditions':TERMS,'/privacy-policy':PRIVACY,'/cookie-policy':COOKIE,'/disclaimer':DISCLAIMER};

const readBody=req=>new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',chunk=>{size+=chunk.length;if(size>100000){reject(new Error('Request too large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)});
const field=(form,key,max=4000)=>String(form.get(key)||'').trim().slice(0,max);
async function handleEnquiry(req,res,type){
  if(req.method!=='POST'){res.statusCode=405;res.setHeader('Allow','POST');return res.end('Method Not Allowed')}
  const raw=await readBody(req),contentType=req.headers['content-type']||'';let form;
  if(contentType.includes('application/json'))form=new Map(Object.entries(JSON.parse(raw.toString('utf8')||'{}')));
  else form=new URLSearchParams(raw.toString('utf8'));
  if(field(form,'website',200)){res.statusCode=200;res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({ok:true}))}
  const name=field(form,'name',160),email=field(form,'email',254),message=field(form,type==='contact'?'message':'notes',6000);
  if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<5){res.statusCode=422;res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({message:'Please complete your name, a valid email address and enquiry details.'}))}
  const reference=`APX-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
  const payload={reference,enquiry_type:type,name,email,phone:field(form,'phone',80)||null,organisation:field(form,'organisation',200)||null,interest:field(form,'interest',200)||null,programme:field(form,'programme',240)||null,learner_count:Number(field(form,'learner_count',8))||null,delivery_format:field(form,'format',100)||null,message};
  const saved=await fetch(`${SUPABASE_URL}/rest/v1/public_enquiries`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)});
  if(!saved.ok){console.error('Enquiry save failed',saved.status,await saved.text());res.statusCode=503;res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({message:'Your enquiry could not be saved right now. Please try again or email info@apexskillsinstitute.co.za.'}))}
  res.statusCode=201;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify({ok:true,reference}));
}

module.exports=async function(req,res){
  try{
    const incoming=new URL(req.url||'/',SITE);
    const p=incoming.pathname;
    if(p==='/api/enquiries')return handleEnquiry(req,res,'contact');
    if(p==='/api/group-training')return handleEnquiry(req,res,'group_training');
    if(p==='/terms'||p==='/terms.html'){res.statusCode=308;res.setHeader('Location','/terms-and-conditions');return res.end()}
    if(p==='/privacy'||p==='/privacy.html'||p==='/popia'||p==='/popia-policy'){res.statusCode=308;res.setHeader('Location','/privacy-policy');return res.end()}
    if(p==='/index'||p==='/index.html'||p.endsWith('.html')){res.statusCode=308;res.setHeader('Location',canonicalRoute(p)+(incoming.search||''));return res.end()}
    if(LEGAL[p]){const b=Buffer.from(LEGAL[p]);res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, must-revalidate');res.setHeader('Content-Length',String(b.length));return res.end(b)}
    let originPath=p;
    if(!/\.[a-z0-9]{2,8}$/i.test(p) && p!=='/') originPath=p+'.html';
    const u=new URL(originPath+incoming.search,ORIGIN);
    const r=await fetch(u,{method:req.method||'GET',headers:{'user-agent':req.headers['user-agent']||'Apex-clean-url-proxy','accept':req.headers.accept||'*/*'}});
    res.statusCode=r.status;
    const type=r.headers.get('content-type')||'';
    for(const [k,v] of r.headers){if(!['content-encoding','content-length','transfer-encoding','connection','location'].includes(k.toLowerCase()))res.setHeader(k,v)}
    if(r.status>=300&&r.status<400&&r.headers.get('location')){const l=r.headers.get('location');res.setHeader('Location',l.replace(/\.html(?=$|[?#])/i,''))}
    res.setHeader('X-Apex-Release-Layer','v2.15-phase1');
    let b=Buffer.from(await r.arrayBuffer());
    if(type.includes('text/html')) b=Buffer.from(cleanHtml(b.toString('utf8'),p),'utf8');
    res.setHeader('Content-Length',String(b.length));
    res.end(b);
  }catch(e){console.error('Apex release proxy failed',e);res.statusCode=503;res.setHeader('Content-Type','text/plain; charset=utf-8');res.end('Apex Skills Institute is temporarily unavailable. Please try again shortly.')}
};
